# Generated by Django 5.2.11 on 2026-05-01 15:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_initial'),
        ('usuarios', '0002_nutritionplan_end_date_nutritionplan_nutritionist_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='weekday',
        ),
        migrations.AddField(
            model_name='appointment',
            name='availability',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment', to='agenda.availability'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='availability',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='availability',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='availability',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ConsultationNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('note_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Agendada'), ('confirmed', 'Confirmada'), ('canceled', 'Cancelada'), ('done', 'Realizada'), ('missed', 'Não compareceu')], default='scheduled', max_length=20)),
                ('observations', models.TextField()),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_notes', to='agenda.appointment')),
                ('nutritionist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_notes', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_notes', to='usuarios.patient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
